import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const defaultSettings = {
  language: 'en',
  background: 'steel',
  theme: 'light'
};

export const backgroundClasses = {
  steel: 'bg-[radial-gradient(circle_at_top_left,rgba(37,99,235,0.16),transparent_34%),linear-gradient(135deg,#f8fafc_0%,#e5e7eb_45%,#cbd5e1_100%)]',
  circuit: 'bg-[linear-gradient(90deg,rgba(15,23,42,0.06)_1px,transparent_1px),linear-gradient(0deg,rgba(15,23,42,0.06)_1px,transparent_1px),linear-gradient(135deg,#f8fafc,#dbeafe)] bg-[size:34px_34px,34px_34px,auto]',
  warehouse: 'bg-[repeating-linear-gradient(135deg,rgba(245,158,11,0.12)_0_12px,transparent_12px_24px),linear-gradient(135deg,#fafafa,#d4d4d8)]',
  carbon: 'bg-[radial-gradient(circle_at_20%_20%,rgba(250,204,21,0.14),transparent_28%),repeating-linear-gradient(45deg,#f5f5f5_0_10px,#e5e7eb_10px_20px)]',
  deepSea: 'bg-[radial-gradient(circle_at_20%_10%,rgba(20,184,166,0.24),transparent_32%),radial-gradient(circle_at_80%_30%,rgba(59,130,246,0.22),transparent_30%),linear-gradient(135deg,#061826_0%,#0f3b52_48%,#082f49_100%)]',
  iron: 'bg-[repeating-linear-gradient(90deg,rgba(15,23,42,0.12)_0_2px,transparent_2px_18px),radial-gradient(circle_at_70%_15%,rgba(244,211,94,0.16),transparent_30%),linear-gradient(135deg,#d1d5db_0%,#71717a_52%,#27272a_100%)]'
};

export const translations = {
  en: {
    // Dashboard (existing)
    dashboard: 'Dashboard',
    admissionForm: 'Admission Form',
    documents: 'Documents',
    settings: 'Settings',
    student: 'Student',
    portal: 'Portal',
    studentPortal: 'Student Portal',
    logout: 'Logout',
    applicant: 'Applicant',
    applicationStatus: 'Application Status',
    academicYear: 'Academic Year 2026-2027',
    draft: 'Draft',
    submitted: 'Submitted',
    underReview: 'Under Review',
    decision: 'Decision',
    continueApplication: 'Continue Application',
    requiredDocuments: 'Required Documents',
    identityCard: 'Identity Card',
    academicTranscript: 'Academic Transcript',
    passportPhoto: 'Passport Photo',
    uploadMissing: 'Upload Missing',
    recentNotifications: 'Recent Notifications',
    settingsIntro: 'Choose your working language and dashboard background.',
    language: 'Language',
    industrialBackground: 'Industrial Background',
    appearance: 'Appearance',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',

    // Nav / Header
    navHome: 'Home',
    navAbout: 'About',
    navFaculties: 'Faculties',
    navContact: 'Contact',
    logIn: 'Log in',
    applyNow: 'Apply Now',

    // WhatsApp
    whatsappLabel: 'Write to us',

    // Footer
    uniName: 'Université Progressiste de Kinshasa',
    footerDesc: 'Empowering the next generation of leaders in Democratic Republic of Congo through excellence in education, research, and innovation.',
    quickLinks: 'Quick Links',
    aboutUs: 'About Us',
    facultiesTitle: 'Faculties',
    admissions: 'Admissions',
    contactTitle: 'Contact',
    addressLine1: '15th Street, Limete Industrial',
    addressLine2: 'Kinshasa, DRC',
    contactEmail: 'info@upk-kinshasa.net',
    contactPhone: '+243 81 000 0000',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    rights: 'All rights reserved.',

    // Hero
    heroBadge: 'Excellence in education since 1994',
    heroTitle: 'Shape your future at the',
    heroHighlight: 'Université Progressiste de Kinshasa',
    heroSub: 'Training the next generation of leaders through world-class education, innovation and research at the heart of the DRC.',
    heroCta: 'Apply for Admission',
    heroDiscover: 'Discover UPK',
    trustEsu: 'Accredited by the Ministry of ESU',
    trustAuf: 'Member of AUF',
    trustIntl: 'Internationally recognized degrees',

    // Why Choose
    whyLabel: 'Why choose us',
    whyTitle: 'Why Choose UPK?',
    whySub: 'We offer a world-class educational experience designed to prepare you for success.',
    whyCard1Title: 'Academic Excellence',
    whyCard1Desc: 'Our renowned professors and industry experts are committed to providing the highest quality education, combining theory and practice.',
    whyCard2Title: 'Modern Facilities',
    whyCard2Desc: 'Cutting-edge laboratories, comprehensive libraries and modern classrooms designed to enhance learning.',
    whyCard3Title: 'Vibrant Campus Life',
    whyCard3Desc: 'Join a diverse community of students engaged in numerous clubs, sports and cultural activities.',

    // Statistics
    statStudents: 'Students Enrolled',
    statPrograms: 'Academic Programs',
    statRate: 'Employment Rate',
    statYears: 'Years of Excellence',

    // Programs section
    progLabel: 'Our Programs',
    progTitle: 'Explore Our Faculties',
    progSub: 'Discover a comprehensive range of programs designed to meet the challenges of the modern world.',
    learnMore: 'Learn more',
    viewAll: 'View all programs',

    // News section
    newsLabel: 'News & Events',
    newsTitle: 'Campus Life & Events',
    newsSub: 'Stay informed about the latest news, events and achievements of our university community.',
    readMore: 'Read more',
    tagEnrollment: 'Enrollment',
    tagExcellence: 'Excellence',
    tagPartnership: 'Partnership',
    news1Title: 'Registration Deadline Approaching',
    news1Desc: 'Registrations for the 2026-2027 academic year are open. Apply before July 30.',
    news2Title: 'UPK Wins National Championship',
    news2Desc: 'Our debate team won first place at the national inter-university championship.',
    news3Title: 'New International Partnership',
    news3Desc: 'UPK signs a collaboration agreement with Paris-Saclay University for academic exchanges.',

    // CTA Banner
    ctaTitle: 'Ready to Join UPK?',
    ctaSub: 'Take the first step towards a promising future. Admissions are open for the 2026-2027 academic year.',
    ctaApply: 'Apply Now',
    ctaContact: 'Contact Us',

    // About page
    aboutTitle: 'About Université Progressiste de Kinshasa',
    aboutDesc: 'The Université Progressiste de Kinshasa (UPK) is one of the premier higher education institutions in the Democratic Republic of Congo. Founded with the mission to provide accessible, high-quality education, UPK has grown into a vibrant center of learning and research.',
    missionTitle: 'Our Mission',
    missionDesc: 'To foster intellectual growth, promote academic excellence, and prepare future leaders who will contribute meaningfully to the socio-economic development of the nation and the world.',
    visionTitle: 'Our Vision',
    visionDesc: 'To be recognized globally as a leading university that drives innovation, research, and holistic education in Africa.',

    // Faculties page
    facultiesLoading: 'Loading faculties...',
    facultiesError: 'Unable to load faculties at this time.',
    facultiesErrorTitle: 'An error occurred',
    facultiesRetry: 'Retry',
    facultiesBannerLabel: 'Excellence in education',
    facultiesTitle: 'Our Faculties',
    facultiesSub: 'Discover our faculties and find the program that matches your ambitions.',
    facultiesEmpty: 'No faculties available',
    departments: 'Departments',
    facultiesCtaTitle: 'Ready to Join UPK?',
    facultiesCtaSub: 'Admissions are open. Apply now for the 2026-2027 academic year.',
    facultiesCtaBtn: 'Apply Now',

    // Login page
    loginTitle: 'Welcome Back',
    loginNoAccount: "Don't have an account?",
    loginApply: 'Apply for admission',
    loginEmailLabel: 'Email Address',
    loginPasswordLabel: 'Password',
    loginEmailPlaceholder: 'Enter your email',
    loginPasswordPlaceholder: 'Enter your password',
    loginRemember: 'Remember me',
    loginForgot: 'Forgot your password?',
    loginButton: 'Sign In',
    loginFailed: 'Login failed. Please check your credentials.',
    loginSuccess: 'Account created successfully! Please check your email and click the confirmation link before logging in.',
    loginVerified: 'Email verified successfully! You can now log in.',

    // Register page
    regTitle: 'Start Your Journey',
    regHaveAccount: 'Already have an account?',
    regSignIn: 'Sign in',
    regFirstName: 'First Name',
    regLastName: 'Last Name',
    regEmailLabel: 'Email Address',
    regPasswordLabel: 'Password',
    regConfirmLabel: 'Confirm Password',
    regFirstNamePlaceholder: 'First Name',
    regLastNamePlaceholder: 'Last Name',
    regEmailPlaceholder: 'Enter your email',
    regPasswordPlaceholder: 'Password',
    regConfirmPlaceholder: 'Confirm password',
    regButton: 'Create Account',
    regRule8_16: '8-16 characters',
    regRuleUpper: '1 uppercase',
    regRuleLower: '1 lowercase',
    regRuleNumber: '1 number',
    regRuleSpecial: '1 special character',
    regMatch: 'Passwords match',
    regNoMatch: 'Passwords do not match',
    regPasswordError: 'Password does not meet all requirements.',
    regConfirmError: 'Passwords do not match.',
    regEmailSent: 'Check your email',
    regEmailSentDesc: 'A confirmation email has been sent to',
    regStepsTitle: 'Next steps:',
    regStep1: 'Open your inbox',
    regStep2: 'Click the confirmation link',
    regStep3: 'Your account will be activated automatically',
    regStep4: 'Log in with your credentials',
    regLinkExpiry: 'The link is valid for 2 hours.',
    regGoLogin: 'Go to login',
    regNotReceived: "Didn't receive the email? Check your spam or",
    regResend: 'resend the link',
    regResendSuccess: 'A new verification email has been sent.',
    regResendError: 'Error resending. Please try again.',
    regSubmitError: 'An error occurred during registration.',

    // Admission Form
    formPersonalInfo: 'Personal Information',
    formProfilePicture: 'Profile Picture',
    formChoosePhoto: 'Choose Photo',
    formFullName: 'Full Name',
    formFullNameRequired: 'Full name is required.',
    formGender: 'Gender',
    formSelectGender: 'Select Gender',
    formMale: 'Male',
    formFemale: 'Female',
    formGenderRequired: 'Gender is required.',
    formMaritalStatus: 'Marital Status',
    formSelectStatus: 'Select Status',
    formSingle: 'Single',
    formMarried: 'Married',
    formDivorced: 'Divorced',
    formWidowed: 'Widowed',
    formMaritalRequired: 'Marital status is required.',
    formDob: 'Date of Birth',
    formDobRequired: 'Date of birth is required.',
    formNationality: 'Nationality',
    formNationalityRequired: 'Nationality is required.',
    formSecondNationality: 'Second Nationality',
    formOptional: '(Optional)',
    formDisability: 'Disability Condition',
    formSelectCondition: 'Select Condition',
    formNoDisability: 'No disability',
    formPhysical: 'Physical disability',
    formVisual: 'Visual impairment',
    formHearing: 'Hearing impairment',
    formLearning: 'Learning disability',
    formDisabilityOther: 'Other',
    formDisabilityRequired: 'Disability condition is required.',
    formPermanentCountry: 'Permanent Country',
    formSameCountry: 'Current country is same',
    formSelectCountry: 'Select Country',
    formPermanentCountryRequired: 'Permanent country is required.',
    formCurrentCountry: 'Current Country',
    formCurrentCountryRequired: 'Current country is required.',
    formPermanentResidence: 'Permanent Residence',
    formPermanentResidenceRequired: 'Permanent residence is required.',
    formCurrentResidence: 'Current Residence',
    formSameResidence: 'Same as permanent',
    formCurrentResidenceRequired: 'Current residence is required.',
    formPhone: 'Phone Number',
    formPhoneRequired: 'Phone number is required.',
    formEmail: 'Email',
    formEmailRequired: 'Email is required.',
    formParentInfo: 'Parent Information',
    formParentName: 'Parent / Guardian Full Name',
    formParentNameRequired: 'Parent full name is required.',
    formRelationship: 'Relationship',
    formSelectRelationship: 'Select Relationship',
    formFather: 'Father',
    formMother: 'Mother',
    formGuardian: 'Guardian',
    formRelationshipRequired: 'Relationship is required.',
    formParentPhone: 'Parent Phone Number',
    formParentPhoneRequired: 'Parent phone number is required.',
    formParentEmail: 'Parent Email',
    formParentEmailRequired: 'Parent email is required.',
    formParentAddress: 'Parent Address',
    formParentAddressRequired: 'Parent address is required.',
    formAcademicBg: 'Academic Background',
    formPreviousSchool: 'Previous School / High School',
    formPreviousSchoolRequired: 'Previous school is required.',
    formSection: 'Section / Option',
    formSectionRequired: 'Section is required.',
    formPercentage: 'Percentage Obtained (%)',
    formPercentageRequired: 'Percentage is required.',
    formProgramSelection: 'Program Selection',
    formFaculty: 'Faculty',
    formSelectFaculty: 'Select Faculty',
    formFacultyRequired: 'Faculty is required.',
    formDepartment: 'Department',
    formSelectDepartment: 'Select Department',
    formDepartmentRequired: 'Department is required.',
    formBack: 'Back',
    formSaveDraft: 'Save Draft',
    formNext: 'Next',
    formSubmit: 'Submit Application',
    formEmptyError: 'Please complete the required fields before submitting.',
    formPhotoRequired: 'Profile picture is required.',

    // Student Dashboard
    dashAppSaved: 'Application Draft Saved',
    dashAppSavedDesc: 'Your application progress has been saved securely.',
    dashAccCreated: 'Account Created Successfully',
    dashAccCreatedDesc: 'Welcome to the UPK online admission portal.',
    dashHoursAgo: 'hours ago',
    dashDayAgo: 'day ago',

    // Documents
    docTitle: 'Document Upload',
    docDesc: 'Please upload clear, legible copies of your documents. PDF, JPG, and PNG are supported (Max 5MB per file).',
    docDiploma: 'Diploma / High School Certificate',
    docTranscript: 'Academic Transcript',
    docPhoto: 'Passport Photo',
    docIdCard: 'Identity Card',
    docBirthCert: 'Birth Certificate',
    docRequired: 'Required',
    docNoFile: 'No file chosen',
    docSelected: 'Selected',
    docUploaded: 'Uploaded',
    docClickOrDrag: 'Click or drag',
    docSubmit: 'Submit Documents',

    // Settings
    langEn: 'English',
    langFr: 'Francais',
    langSw: 'Kiswahili',
    langLn: 'Lingala',
    langLua: 'Tshiluba',
    langKg: 'Kikongo',
    bgSteel: 'Steel Plant',
    bgCircuit: 'Circuit Floor',
    bgWarehouse: 'Warehouse Lines',
    bgCarbon: 'Carbon Grid',
    bgDeepSea: 'Deep Sea',
    bgIron: 'Iron Works',

    // Admin Dashboard
    adminTotalApps: 'Total Applications',
    adminPending: 'Pending Review',
    adminApproved: 'Approved',
    adminRejected: 'Rejected',
    adminAppsOverview: 'Applications Overview',
    adminByFaculty: 'By Faculty',

    // Admin Applications
    appTitle: 'Applications',
    appFilter: 'Filter',
    appExport: 'Export',
    appSearch: 'Search by name, ID, or faculty...',
    appId: 'ID',
    appName: 'Applicant Name',
    appFaculty: 'Faculty',
    appDate: 'Date Applied',
    appStatus: 'Status',
    appActions: 'Actions',
    appStatusPending: 'Pending',
    appStatusApproved: 'Approved',
    appStatusRejected: 'Rejected',
    appShowing: 'Showing',
    appTo: 'to',
    appOf: 'of',
    appEntries: 'entries',
    appPrev: 'Prev',
    appNext: 'Next',

    // Admin Faculties
    facManage: 'Faculties Management',
    facAddFaculty: 'Add Faculty',
    facDepartments: 'Departments',
    facActive: 'Active',
    facInactive: 'Inactive',
    facAddDept: 'Add Department',

    // Contact page
    contactTitle: 'Contact Us',
    contactDesc: 'Have questions about admissions or programs? Our team is here to help you.',
    contactVisit: 'Visit Us',
    contactCall: 'Call Us',
    contactEmailTitle: 'Email Us',
    contactPhone2: '+243 82 000 0000',
    contactEmail2: 'admissions@upk-kinshasa.net',

    // Verify Email
    verifyLoading: 'Verifying your email...',
    verifySuccess: 'Email Verified!',
    verifySuccessMsg: 'Email verified successfully!',
    verifyGoLogin: 'Go to login',
    verifyFail: 'Verification Failed',
    verifyMissingToken: 'Missing verification token. Make sure you clicked the full link from the email.',
    verifyExpired: 'The verification link is invalid or has expired. Please create a new account or contact support.',
    verifyHint: 'Make sure you are using the most recent link from your email. Each link can only be used once and expires after 2 hours.',
    verifyNewAccount: 'Create a new account',
    verifyBack: 'Back',
  },
  fr: {
    // Dashboard
    dashboard: 'Tableau de bord',
    admissionForm: "Formulaire d'admission",
    documents: 'Documents',
    settings: 'Paramètres',
    student: 'Étudiant',
    portal: 'Portail',
    studentPortal: 'Portail Étudiant',
    logout: 'Déconnexion',
    applicant: 'Candidat',
    applicationStatus: "Statut de la candidature",
    academicYear: 'Année académique 2026-2027',
    draft: 'Brouillon',
    submitted: 'Soumis',
    underReview: 'En révision',
    decision: 'Décision',
    continueApplication: 'Continuer la candidature',
    requiredDocuments: 'Documents requis',
    identityCard: "Carte d'identité",
    academicTranscript: 'Relevé de notes',
    passportPhoto: 'Photo d\'identité',
    uploadMissing: 'Téléverser les documents manquants',
    recentNotifications: 'Notifications récentes',
    settingsIntro: 'Choisissez votre langue de travail et l\'arrière-plan du tableau de bord.',
    language: 'Langue',
    industrialBackground: 'Arrière-plan industriel',
    appearance: 'Apparence',
    lightMode: 'Mode clair',
    darkMode: 'Mode sombre',

    // Nav / Header
    navHome: 'Accueil',
    navAbout: 'À propos',
    navFaculties: 'Facultés',
    navContact: 'Contact',
    logIn: 'Connexion',
    applyNow: 'Postuler',

    // WhatsApp
    whatsappLabel: 'Écrivez-nous',

    // Footer
    uniName: 'Université Progressiste de Kinshasa',
    footerDesc: 'Former la prochaine génération de leaders en République Démocratique du Congo grâce à l\'excellence en éducation, recherche et innovation.',
    quickLinks: 'Liens rapides',
    aboutUs: 'À propos',
    facultiesTitle: 'Facultés',
    admissions: 'Admissions',
    contactTitle: 'Contact',
    addressLine1: '15e Avenue, Limete Industriel',
    addressLine2: 'Kinshasa, RDC',
    contactEmail: 'info@upk-kinshasa.net',
    contactPhone: '+243 81 000 0000',
    privacy: 'Politique de confidentialité',
    terms: 'Conditions d\'utilisation',
    rights: 'Tous droits réservés.',

    // Hero
    heroBadge: "Formation d'excellence depuis 1994",
    heroTitle: 'Façonnez votre avenir à l\'',
    heroHighlight: 'Université Progressiste de Kinshasa',
    heroSub: 'Former la prochaine génération de leaders grâce à une éducation de classe mondiale, l\'innovation et la recherche au cœur de la RDC.',
    heroCta: 'Postuler à l\'admission',
    heroDiscover: 'Découvrir l\'UPK',
    trustEsu: 'Accrédité par le Ministère de l\'ESU',
    trustAuf: 'Membre de l\'AUF',
    trustIntl: 'Diplômes reconnus à l\'international',

    // Why Choose
    whyLabel: 'Pourquoi nous choisir',
    whyTitle: 'Pourquoi Choisir l\'UPK ?',
    whySub: 'Nous offrons une expérience éducative de classe mondiale conçue pour vous préparer au succès.',
    whyCard1Title: 'Excellence Pédagogique',
    whyCard1Desc: 'Nos professeurs de renom et experts du secteur s\'engagent à fournir une éducation de la plus haute qualité, alliant théorie et pratique.',
    whyCard2Title: 'Installations Modernes',
    whyCard2Desc: 'Laboratoires à la pointe de la technologie, bibliothèques complètes et salles de classe modernes conçues pour améliorer l\'apprentissage.',
    whyCard3Title: 'Vie Campus Vibrante',
    whyCard3Desc: 'Rejoignez une communauté diversifiée d\'étudiants engagés dans de nombreux clubs, sports et activités culturelles.',

    // Statistics
    statStudents: 'Étudiants Inscrits',
    statPrograms: 'Programmes Académiques',
    statRate: "Taux d'Insertion",
    statYears: "Années d'Excellence",

    // Programs section
    progLabel: 'Nos Programmes',
    progTitle: 'Explorez Nos Facultés',
    progSub: 'Découvrez une gamme complète de programmes conçus pour répondre aux défis du monde moderne.',
    learnMore: 'En savoir plus',
    viewAll: 'Voir tous les programmes',

    // News section
    newsLabel: 'Actualités',
    newsTitle: 'Vie du Campus & Événements',
    newsSub: 'Restez informé des dernières nouvelles, événements et réalisations de notre communauté universitaire.',
    readMore: 'Lire plus',
    tagEnrollment: 'Inscriptions',
    tagExcellence: 'Excellence',
    tagPartnership: 'Partenariat',
    news1Title: 'Date Limite d\'Inscription Approchante',
    news1Desc: 'Les inscriptions pour l\'année académique 2026-2027 sont ouvertes. Postulez avant le 30 juillet.',
    news2Title: 'L\'UPK Remporte le Championnat National',
    news2Desc: 'Notre équipe de débat a remporté la première place au championnat national inter-universitaire.',
    news3Title: 'Nouveau Partenariat International',
    news3Desc: 'L\'UPK signe un accord de collaboration avec l\'Université Paris-Saclay pour des échanges académiques.',

    // CTA Banner
    ctaTitle: 'Prêt à Rejoindre l\'UPK ?',
    ctaSub: 'Faites le premier pas vers un avenir prometteur. Les admissions sont ouvertes pour l\'année académique 2026-2027.',
    ctaApply: 'Postuler maintenant',
    ctaContact: 'Nous contacter',

    // About page
    aboutTitle: 'À propos de l\'Université Progressiste de Kinshasa',
    aboutDesc: 'L\'Université Progressiste de Kinshasa (UPK) est l\'une des principales institutions d\'enseignement supérieur en République Démocratique du Congo. Fondée avec la mission de fournir une éducation accessible et de haute qualité, l\'UPK est devenue un centre dynamique d\'apprentissage et de recherche.',
    missionTitle: 'Notre Mission',
    missionDesc: 'Favoriser la croissance intellectuelle, promouvoir l\'excellence académique et préparer les futurs leaders qui contribueront de manière significative au développement socio-économique de la nation et du monde.',
    visionTitle: 'Notre Vision',
    visionDesc: 'Être reconnue mondialement comme une université de premier plan qui stimule l\'innovation, la recherche et l\'éducation holistique en Afrique.',

    // Faculties page
    facultiesLoading: 'Chargement des facultés...',
    facultiesError: 'Impossible de charger les facultés pour le moment.',
    facultiesErrorTitle: 'Une erreur est survenue',
    facultiesRetry: 'Réessayer',
    facultiesBannerLabel: 'Formation d\'excellence',
    facultiesTitle: 'Nos Facultés',
    facultiesSub: 'Découvrez nos facultés et trouvez le programme qui correspond à vos ambitions.',
    facultiesEmpty: 'Aucune faculté disponible',
    departments: 'Départements',
    facultiesCtaTitle: 'Prêt à Rejoindre l\'UPK ?',
    facultiesCtaSub: 'Les admissions sont ouvertes. Postulez dès maintenant pour l\'année académique 2026-2027.',
    facultiesCtaBtn: 'Postuler maintenant',

    // Login page
    loginTitle: 'Bon retour',
    loginNoAccount: 'Vous n\'avez pas de compte ?',
    loginApply: 'Postuler à l\'admission',
    loginEmailLabel: 'Adresse email',
    loginPasswordLabel: 'Mot de passe',
    loginEmailPlaceholder: 'Entrez votre email',
    loginPasswordPlaceholder: 'Entrez votre mot de passe',
    loginRemember: 'Se souvenir de moi',
    loginForgot: 'Mot de passe oublié ?',
    loginButton: 'Se connecter',
    loginFailed: 'Échec de connexion. Vérifiez vos identifiants.',
    loginSuccess: 'Compte créé avec succès ! Veuillez vérifier votre boîte email et cliquer sur le lien de confirmation avant de vous connecter.',
    loginVerified: 'Email vérifié avec succès ! Vous pouvez maintenant vous connecter.',

    // Register page
    regTitle: 'Commencez votre parcours',
    regHaveAccount: 'Vous avez déjà un compte ?',
    regSignIn: 'Se connecter',
    regFirstName: 'Prénom',
    regLastName: 'Nom',
    regEmailLabel: 'Adresse email',
    regPasswordLabel: 'Mot de passe',
    regConfirmLabel: 'Confirmer le mot de passe',
    regFirstNamePlaceholder: 'Prénom',
    regLastNamePlaceholder: 'Nom',
    regEmailPlaceholder: 'Entrez votre email',
    regPasswordPlaceholder: 'Mot de passe',
    regConfirmPlaceholder: 'Confirmer le mot de passe',
    regButton: 'Créer un compte',
    regRule8_16: '8-16 caractères',
    regRuleUpper: '1 majuscule',
    regRuleLower: '1 minuscule',
    regRuleNumber: '1 chiffre',
    regRuleSpecial: '1 caractère spécial',
    regMatch: 'Mots de passe identiques',
    regNoMatch: 'Les mots de passe ne correspondent pas',
    regPasswordError: 'Le mot de passe ne respecte pas toutes les exigences.',
    regConfirmError: 'Les mots de passe ne correspondent pas.',
    regEmailSent: 'Vérifiez votre email',
    regEmailSentDesc: 'Un email de confirmation a été envoyé à',
    regStepsTitle: 'Prochaines étapes :',
    regStep1: 'Ouvrez votre boîte de réception',
    regStep2: 'Cliquez sur le lien de confirmation',
    regStep3: 'Votre compte sera activé automatiquement',
    regStep4: 'Connectez-vous avec vos identifiants',
    regLinkExpiry: 'Le lien est valable 2 heures.',
    regGoLogin: 'Aller à la connexion',
    regNotReceived: "Vous n'avez pas reçu l'email ? Vérifiez vos spams ou",
    regResend: 'renvoyez le lien',
    regResendSuccess: 'Un nouvel email de vérification a été envoyé.',
    regResendError: 'Erreur lors du renvoi. Veuillez réessayer.',
    regSubmitError: 'Une erreur est survenue lors de l\'inscription.',

    // Admission Form
    formPersonalInfo: 'Informations personnelles',
    formProfilePicture: 'Photo de profil',
    formChoosePhoto: 'Choisir une photo',
    formFullName: 'Nom complet',
    formFullNameRequired: 'Le nom complet est requis.',
    formGender: 'Genre',
    formSelectGender: 'Sélectionnez le genre',
    formMale: 'Masculin',
    formFemale: 'Féminin',
    formGenderRequired: 'Le genre est requis.',
    formMaritalStatus: 'Situation matrimoniale',
    formSelectStatus: 'Sélectionnez le statut',
    formSingle: 'Célibataire',
    formMarried: 'Marié(e)',
    formDivorced: 'Divorcé(e)',
    formWidowed: 'Veuf/Veuve',
    formMaritalRequired: 'La situation matrimoniale est requise.',
    formDob: 'Date de naissance',
    formDobRequired: 'La date de naissance est requise.',
    formNationality: 'Nationalité',
    formNationalityRequired: 'La nationalité est requise.',
    formSecondNationality: 'Deuxième nationalité',
    formOptional: '(Optionnel)',
    formDisability: 'Condition de handicap',
    formSelectCondition: 'Sélectionnez la condition',
    formNoDisability: 'Aucun handicap',
    formPhysical: 'Handicap physique',
    formVisual: 'Déficience visuelle',
    formHearing: 'Déficience auditive',
    formLearning: 'Trouble d\'apprentissage',
    formDisabilityOther: 'Autre',
    formDisabilityRequired: 'La condition de handicap est requise.',
    formPermanentCountry: 'Pays permanent',
    formSameCountry: 'Le pays actuel est le même',
    formSelectCountry: 'Sélectionnez le pays',
    formPermanentCountryRequired: 'Le pays permanent est requis.',
    formCurrentCountry: 'Pays actuel',
    formCurrentCountryRequired: 'Le pays actuel est requis.',
    formPermanentResidence: 'Résidence permanente',
    formPermanentResidenceRequired: 'La résidence permanente est requise.',
    formCurrentResidence: 'Résidence actuelle',
    formSameResidence: 'Identique à la résidence permanente',
    formCurrentResidenceRequired: 'La résidence actuelle est requise.',
    formPhone: 'Numéro de téléphone',
    formPhoneRequired: 'Le numéro de téléphone est requis.',
    formEmail: 'Email',
    formEmailRequired: 'L\'email est requis.',
    formParentInfo: 'Informations parentales',
    formParentName: 'Nom du parent / tuteur',
    formParentNameRequired: 'Le nom du parent est requis.',
    formRelationship: 'Relation',
    formSelectRelationship: 'Sélectionnez la relation',
    formFather: 'Père',
    formMother: 'Mère',
    formGuardian: 'Tuteur',
    formRelationshipRequired: 'La relation est requise.',
    formParentPhone: 'Téléphone du parent',
    formParentPhoneRequired: 'Le téléphone du parent est requis.',
    formParentEmail: 'Email du parent',
    formParentEmailRequired: 'L\'email du parent est requis.',
    formParentAddress: 'Adresse du parent',
    formParentAddressRequired: 'L\'adresse du parent est requise.',
    formAcademicBg: 'Parcours académique',
    formPreviousSchool: 'École précédente / Lycée',
    formPreviousSchoolRequired: 'L\'école précédente est requise.',
    formSection: 'Section / Option',
    formSectionRequired: 'La section est requise.',
    formPercentage: 'Pourcentage obtenu (%)',
    formPercentageRequired: 'Le pourcentage est requis.',
    formProgramSelection: 'Sélection du programme',
    formFaculty: 'Faculté',
    formSelectFaculty: 'Sélectionnez la faculté',
    formFacultyRequired: 'La faculté est requise.',
    formDepartment: 'Département',
    formSelectDepartment: 'Sélectionnez le département',
    formDepartmentRequired: 'Le département est requis.',
    formBack: 'Retour',
    formSaveDraft: 'Sauvegarder',
    formNext: 'Suivant',
    formSubmit: 'Soumettre la candidature',
    formEmptyError: 'Veuillez remplir tous les champs requis avant de soumettre.',
    formPhotoRequired: 'La photo de profil est requise.',

    // Student Dashboard
    dashAppSaved: 'Brouillon de candidature sauvegardé',
    dashAppSavedDesc: 'Votre progression a été sauvegardée en toute sécurité.',
    dashAccCreated: 'Compte créé avec succès',
    dashAccCreatedDesc: 'Bienvenue sur le portail d\'admission en ligne de l\'UPK.',
    dashHoursAgo: 'heures',
    dashDayAgo: 'jour',

    // Documents
    docTitle: 'Téléchargement des documents',
    docDesc: 'Veuillez télécharger des copies claires et lisibles de vos documents. PDF, JPG et PNG sont acceptés (Max 5Mo par fichier).',
    docDiploma: 'Diplôme / Certificat d\'études secondaires',
    docTranscript: 'Relevé de notes',
    docPhoto: 'Photo d\'identité',
    docIdCard: 'Carte d\'identité',
    docBirthCert: 'Acte de naissance',
    docRequired: 'Requis',
    docNoFile: 'Aucun fichier choisi',
    docSelected: 'Sélectionné',
    docUploaded: 'Téléchargé',
    docClickOrDrag: 'Cliquez ou glissez',
    docSubmit: 'Soumettre les documents',

    // Settings
    langEn: 'Anglais',
    langFr: 'Français',
    langSw: 'Kiswahili',
    langLn: 'Lingala',
    langLua: 'Tshiluba',
    langKg: 'Kikongo',
    bgSteel: 'Aciérie',
    bgCircuit: 'Sol de circuit',
    bgWarehouse: 'Lignes d\'entrepôt',
    bgCarbon: 'Grille de carbone',
    bgDeepSea: 'Mer profonde',
    bgIron: 'Forge de fer',

    // Admin Dashboard
    adminTotalApps: 'Total des candidatures',
    adminPending: 'En attente',
    adminApproved: 'Approuvées',
    adminRejected: 'Rejetées',
    adminAppsOverview: 'Aperçu des candidatures',
    adminByFaculty: 'Par faculté',

    // Admin Applications
    appTitle: 'Candidatures',
    appFilter: 'Filtrer',
    appExport: 'Exporter',
    appSearch: 'Rechercher par nom, ID ou faculté...',
    appId: 'ID',
    appName: 'Candidat',
    appFaculty: 'Faculté',
    appDate: 'Date de soumission',
    appStatus: 'Statut',
    appActions: 'Actions',
    appStatusPending: 'En attente',
    appStatusApproved: 'Approuvé',
    appStatusRejected: 'Rejeté',
    appShowing: 'Affichage',
    appTo: 'à',
    appOf: 'sur',
    appEntries: 'entrées',
    appPrev: 'Préc',
    appNext: 'Suiv',

    // Admin Faculties
    facManage: 'Gestion des facultés',
    facAddFaculty: 'Ajouter une faculté',
    facDepartments: 'Départements',
    facActive: 'Actif',
    facInactive: 'Inactif',
    facAddDept: 'Ajouter un département',

    // Contact page
    contactTitle: 'Contactez-nous',
    contactDesc: 'Des questions sur les admissions ou les programmes ? Notre équipe est là pour vous aider.',
    contactVisit: 'Nous rendre visite',
    contactCall: 'Nous appeler',
    contactEmailTitle: 'Nous écrire',
    contactPhone2: '+243 82 000 0000',
    contactEmail2: 'admissions@upk-kinshasa.net',

    // Verify Email
    verifyLoading: 'Vérification de votre email en cours...',
    verifySuccess: 'Email vérifié !',
    verifySuccessMsg: 'Email vérifié avec succès !',
    verifyGoLogin: 'Aller à la connexion',
    verifyFail: 'Échec de la vérification',
    verifyMissingToken: 'Token de vérification manquant. Vérifiez que vous avez bien cliqué sur le lien complet reçu par email.',
    verifyExpired: 'Le lien de vérification est invalide ou a expiré. Veuillez créer un nouveau compte ou contacter le support.',
    verifyHint: 'Assurez-vous d\'utiliser le lien le plus récent reçu par email. Chaque lien ne peut être utilisé qu\'une seule fois et expire après 2 heures.',
    verifyNewAccount: 'Créer un nouveau compte',
    verifyBack: 'Retour',
  },
  sw: {
    dashboard: 'Dashibodi',
    admissionForm: 'Fomu ya maombi',
    documents: 'Nyaraka',
    settings: 'Mipangilio',
    student: 'Mwanafunzi',
    portal: 'Tovuti',
    studentPortal: 'Tovuti ya Mwanafunzi',
    logout: 'Toka',
    applicant: 'Mwombaji',
    applicationStatus: 'Hali ya maombi',
    academicYear: 'Mwaka wa masomo 2026-2027',
    draft: 'Rasimu',
    submitted: 'Imewasilishwa',
    underReview: 'Inakaguliwa',
    decision: 'Uamuzi',
    continueApplication: 'Endelea na maombi',
    requiredDocuments: 'Nyaraka zinazohitajika',
    identityCard: 'Kitambulisho',
    academicTranscript: 'Matokeo ya masomo',
    passportPhoto: 'Picha ya pasipoti',
    uploadMissing: 'Pakia zilizokosekana',
    recentNotifications: 'Taarifa za hivi karibuni',
    settingsIntro: 'Chagua lugha ya kazi na mandharinyuma.',
    language: 'Lugha',
    industrialBackground: 'Mandharinyuma ya viwanda',
    appearance: 'Muonekano',
    lightMode: 'Hali angavu',
    darkMode: 'Hali nyeusi',

    navHome: 'Nyumbani',
    navAbout: 'Kuhusu',
    navFaculties: 'Vitivo',
    navContact: 'Wasiliana',
    logIn: 'Ingia',
    applyNow: 'Omba Sasa',
    whatsappLabel: 'Tuandikie',
    uniName: 'Université Progressiste de Kinshasa',
    footerDesc: 'Kuwawezesha kizazi kijacho cha viongozi katika Jamhuri ya Kidemokrasia ya Kongo kupitia ubora wa elimu, utafiti na uvumbuzi.',
    quickLinks: 'Viungo vya haraka',
    aboutUs: 'Kuhusu sisi',
    facultiesTitle: 'Vitivo',
    admissions: 'Maombi',
    contactTitle: 'Wasiliana',
    addressLine1: 'Barabara ya 15, Limete Industrial',
    addressLine2: 'Kinshasa, DRC',
    contactEmail: 'info@upk-kinshasa.net',
    contactPhone: '+243 81 000 0000',
    privacy: 'Sera ya faragha',
    terms: 'Sheria na masharti',
    rights: 'Haki zote zimehifadhiwa.',
    heroBadge: 'Ubora wa elimu tangu 1994',
    heroTitle: 'Undaa mustakabali wako katika',
    heroHighlight: 'Université Progressiste de Kinshasa',
    heroSub: 'Kuandaa kizazi kijacho cha viongozi kupitia elimu ya kiwango cha kimataifa, uvumbuzi na utafiti katikati ya DRC.',
    heroCta: 'Omba Kujiunga',
    heroDiscover: 'Gundua UPK',
    trustEsu: 'Kuthibitishwa na Wizara ya ESU',
    trustAuf: 'Mwanachama wa AUF',
    trustIntl: 'Shahada zinazotambuliwa kimataifa',
    whyLabel: 'Kwa nini tutuchague',
    whyTitle: 'Kwa Nini Chagua UPK?',
    whySub: 'Tunatoa uzoefu wa elimu wa kiwango cha kimataifa iliyoundwa kukutayarisha kwa mafanikio.',
    whyCard1Title: 'Ubora wa Kielimu',
    whyCard1Desc: 'Maprofesa wetu mashuhuri na wataalamu wa sekta wamejikita kutoa elimu ya hali ya juu, kuchanganya nadharia na vitendo.',
    whyCard2Title: 'Vifaa vya Kisasa',
    whyCard2Desc: 'Maabara za kisasa, maktaba kamili na madarasa ya kisasa yaliyoundwa kuongeza ujifunzaji.',
    whyCard3Title: 'Maisha ya Chuo Yenye Nguvu',
    whyCard3Desc: 'Jiunge na jamii mbalimbali za wanafunzi wanaojishughulisha na klabu nyingi, michezo na shughuli za kitamaduni.',
    statStudents: 'Wanafunzi Waliojiandikisha',
    statPrograms: 'Programu za Masomo',
    statRate: 'Kiwango cha Ajira',
    statYears: 'Miaka ya Ubora',
    progLabel: 'Programu Zetu',
    progTitle: 'Gundua Vitivo Vyetu',
    progSub: 'Gundua anuwai kamili ya programu iliyoundwa kukidhi changamoto za ulimwengu wa kisasa.',
    learnMore: 'Jifunze zaidi',
    viewAll: 'Tazama programu zote',
    newsLabel: 'Habari',
    newsTitle: 'Maisha ya Chuo na Matukio',
    newsSub: 'Endelea kufahamishwa kuhusu habari mpya, matukio na mafanikio ya jamii yetu ya chuo kikuu.',
    readMore: 'Soma zaidi',
    tagEnrollment: 'Usajili',
    tagExcellence: 'Ubora',
    tagPartnership: 'Ushirikiano',
    news1Title: 'Tarehe ya Mwisho ya Usajili Inakaribia',
    news1Desc: 'Usajili kwa mwaka wa masomo 2026-2027 uko wazi. Omba kabla ya Julai 30.',
    news2Title: 'UPK Inashinda Mashindano ya Kitaifa',
    news2Desc: 'Timu yetu ya mjadala ilishinda nafasi ya kwanza kwenye mashindano ya kitaifa kati ya vyuo vikuu.',
    news3Title: 'Ushirikiano Mpya wa Kimataifa',
    news3Desc: 'UPK inasaini makubaliano ya ushirikiano na Chuo Kikuu cha Paris-Saclay kwa kubadilishana kitaaluma.',
    ctaTitle: 'Tayari Kujiunga na UPK?',
    ctaSub: 'Chukua hatua ya kwanza kuelekea maisha bora ya baadaye. Maombi yapo wazi kwa mwaka wa masomo 2026-2027.',
    ctaApply: 'Omba Sasa',
    ctaContact: 'Wasiliana Nasi',
    aboutTitle: 'Kuhusu Université Progressiste de Kinshasa',
    aboutDesc: 'Université Progressiste de Kinshasa (UPK) ni moja ya taasisi kuu za elimu ya juu katika Jamhuri ya Kidemokrasia ya Kongo. Ilianzishwa kwa lengo la kutoa elimu inayoweza kupatikana na ya hali ya juu, UPK imekua na kuwa kituo cha nguvu cha kujifunza na utafiti.',
    missionTitle: 'Dhamira Yetu',
    missionDesc: 'Kukuza ukuaji wa kiakili, kukuza ubora wa kitaaluma, na kuandaa viongozi wa baadaye wanaochangia kwa maana katika maendeleo ya kijamii na kiuchumi ya taifa na ulimwengu.',
    visionTitle: 'Maono Yetu',
    visionDesc: 'Kutambuliwa kimataifa kama chuo kikuu kinachoongoza kinachoendesha uvumbuzi, utafiti, na elimu kamili barani Afrika.',
    facultiesLoading: 'Inapakia vitivo...',
    facultiesError: 'Haikuweza kupakia vitivo kwa sasa.',
    facultiesErrorTitle: 'Hitilafu imetokea',
    facultiesRetry: 'Jaribu tena',
    facultiesBannerLabel: 'Ubora wa elimu',
    facultiesTitle: 'Vitivo Vyetu',
    facultiesSub: 'Gundua vitivo vyetu na upate programu inayolingana na matarajio yako.',
    facultiesEmpty: 'Hakuna vitivo vinavyopatikana',
    departments: 'Idara',
    facultiesCtaTitle: 'Tayari Kujiunga na UPK?',
    facultiesCtaSub: 'Maombi yapo wazi. Omba sasa kwa mwaka wa masomo 2026-2027.',
    facultiesCtaBtn: 'Omba Sasa',
    loginTitle: 'Karibu Tena',
    loginNoAccount: 'Huna akaunti?',
    loginApply: 'Omba kujiunga',
    loginEmailLabel: 'Barua pepe',
    loginPasswordLabel: 'Nywila',
    loginEmailPlaceholder: 'Ingiza barua pepe yako',
    loginPasswordPlaceholder: 'Ingiza nywila yako',
    loginRemember: 'Nikumbuke',
    loginForgot: 'Umesahau nywila?',
    loginButton: 'Ingia',
    loginFailed: 'Kuingia kumeshindwa. Tafadhali angalia kitambulisho chako.',
    loginSuccess: 'Akaunti imeundwa kwa mafanikio! Tafadhali angalia barua pepe yako na ubofye kiungo cha kuthibitisha kabla ya kuingia.',
    loginVerified: 'Barua pepe imethibitishwa kwa mafanikio! Unaweza kuingia sasa.',
    regTitle: 'Anza Safari Yako',
    regHaveAccount: 'Tayari una akaunti?',
    regSignIn: 'Ingia',
    regFirstName: 'Jina la Kwanza',
    regLastName: 'Jina la Mwisho',
    regEmailLabel: 'Barua pepe',
    regPasswordLabel: 'Nywila',
    regConfirmLabel: 'Thibitisha Nywila',
    regFirstNamePlaceholder: 'Jina la Kwanza',
    regLastNamePlaceholder: 'Jina la Mwisho',
    regEmailPlaceholder: 'Ingiza barua pepe yako',
    regPasswordPlaceholder: 'Nywila',
    regConfirmPlaceholder: 'Thibitisha nywila',
    regButton: 'Fungua Akaunti',
    regRule8_16: 'Herufi 8-16',
    regRuleUpper: '1 herufi kubwa',
    regRuleLower: '1 herufi ndogo',
    regRuleNumber: '1 nambari',
    regRuleSpecial: '1 alama maalum',
    regMatch: 'Nywila zinalingana',
    regNoMatch: 'Nywila hazilingani',
    regPasswordError: 'Nywila haikidhi mahitaji yote.',
    regConfirmError: 'Nywila hazilingani.',
    regEmailSent: 'Angalia barua pepe yako',
    regEmailSentDesc: 'Barua pepe ya kuthibitisha imetumwa kwa',
    regStepsTitle: 'Hatua zinazofuata:',
    regStep1: 'Fungua kikasha chako',
    regStep2: 'Bofya kiungo cha kuthibitisha',
    regStep3: 'Akaunti yako itawashwa kiotomatiki',
    regStep4: 'Ingia kwa kutumia kitambulisho chako',
    regLinkExpiry: 'Kiungo ni halali kwa masaa 2.',
    regGoLogin: 'Nenda kwenye kuingia',
    regNotReceived: 'Hukupata barua pepe? Angalia spam yako au',
    regResend: 'tuma kiungo tena',
    regResendSuccess: 'Barua pepe mpya ya kuthibitisha imetumwa.',
    regResendError: 'Hitilafu katika kutuma tena. Tafadhali jaribu tena.',
    regSubmitError: 'Kosa limetokea wakati wa usajili.',

    contactTitle: 'Wasiliana Nasi',
    contactDesc: 'Una maswali kuhusu maombi au programu? Timu yetu iko hapa kukusaidia.',
    contactVisit: 'Tutembelee',
    contactCall: 'Tupigie Simu',
    contactEmailTitle: 'Tutumie Barua Pepe',
    contactPhone2: '+243 82 000 0000',
    contactEmail2: 'admissions@upk-kinshasa.net',

    verifyLoading: 'Inathibitisha barua pepe yako...',
    verifySuccess: 'Barua Pepe Imethibitishwa!',
    verifySuccessMsg: 'Barua pepe imethibitishwa kwa mafanikio!',
    verifyGoLogin: 'Nenda kwenye kuingia',
    verifyFail: 'Uthibitishaji Umeshindwa',
    verifyMissingToken: 'Token ya uthibitishaji haipo. Hakikisha umebofya kiungo kamili kutoka kwa barua pepe.',
    verifyExpired: 'Kiungo cha uthibitishaji ni batili au kimeisha. Tafadhali unda akaunti mpya au wasiliana na msaada.',
    verifyHint: 'Hakikisha unatumia kiungo cha hivi karibuni kutoka kwa barua pepe yako. Kila kiungo kinaweza kutumika mara moja tu na kinaisha baada ya masaa 2.',
    verifyNewAccount: 'Unda akaunti mpya',
    verifyBack: 'Nyuma',
  },
  ln: {
    dashboard: 'Etando',
    admissionForm: 'Formilere ya kokota',
    documents: 'Mikanda',
    settings: 'Bobongisi',
    student: 'Moyekoli',
    portal: 'Portal',
    studentPortal: 'Portal ya Moyekoli',
    logout: 'Bima',
    applicant: 'Mosengi',
    applicationStatus: 'Ezaleli ya bosengi',
    academicYear: 'Mobu ya kelasi 2026-2027',
    draft: 'Brouillon',
    submitted: 'Etindami',
    underReview: 'Na botali',
    decision: 'Ekateli',
    continueApplication: 'Koba bosengi',
    requiredDocuments: 'Mikanda esengeli',
    identityCard: 'Carte ya identité',
    academicTranscript: 'Releve ya kelasi',
    passportPhoto: 'Foto passeport',
    uploadMissing: 'Tia oyo ezangi',
    recentNotifications: 'Mayebisi ya sika',
    settingsIntro: 'Pona monoko ya mosala mpe fond.',
    language: 'Monoko',
    industrialBackground: 'Fond industriel',
    appearance: 'Lolenge',
    lightMode: 'Mode polele',
    darkMode: 'Mode molili',

    navHome: 'Ebandeli',
    navAbout: 'Mpo na',
    navFaculties: 'Mikanda',
    navContact: 'Boyokani',
    logIn: 'Kota',
    applyNow: 'Senga',
    whatsappLabel: 'Komela biso',
    uniName: 'Université Progressiste de Kinshasa',
    footerDesc: 'Kopesa nguvu na libota liye ya bakonzi na République Démocratique ya Congo na nzela ya boyebi, bolukiluki mpe bobwasi.',
    quickLinks: 'Binginya',
    aboutUs: 'Mpo na biso',
    facultiesTitle: 'Mikanda',
    admissions: 'Bosengi',
    contactTitle: 'Boyokani',
    addressLine1: 'Nzeta 15, Limete Industriel',
    addressLine2: 'Kinshasa, RDC',
    contactEmail: 'info@upk-kinshasa.net',
    contactPhone: '+243 81 000 0000',
    privacy: 'Mibeko ya bobombami',
    terms: 'Mibeko ya kosalela',
    rights: 'Makoki manso ebatelami.',
    heroBadge: 'Boyebi ya likambo uta 1994',
    heroTitle: 'Bobongisa libaku na yo na',
    heroHighlight: 'Université Progressiste de Kinshasa',
    heroSub: 'Kokolisa libota liye ya bakonzi na nzela ya boyebi ya mokili mobimba, bolukiluki mpe bobwasi na motema ya RDC.',
    heroCta: 'Senga mpo na kokota',
    heroDiscover: 'Yeba UPK',
    trustEsu: 'Endimami na Ministère ya ESU',
    trustAuf: 'Mokambi ya AUF',
    trustIntl: 'Bazelu bayebani na mokili mobimba',
    whyLabel: 'Mpo na nini topona biso',
    whyTitle: 'Mpo na nini topona UPK?',
    whySub: 'Topesaka boyebi ya mokili mobimba mpo na kokomisa yo na kolonga.',
    whyCard1Title: 'Boyebi ya Likambo',
    whyCard1Desc: 'Baprofese na biso ya lokumu mpe bayebi ya mosala bapesaka boyebi ya likolo koleka, kosangisa mayekoli mpe mosala.',
    whyCard2Title: 'Biloko ya Sika',
    whyCard2Desc: 'Bilabɔ ya sika, babibliotɛki ya kokoka mpe bakelasi ya sika mpo na kokolisa boyekoli.',
    whyCard3Title: 'Bomoi ya Campus',
    whyCard3Desc: 'Sangela lisanga ya bayekoli ekeseni oyo bazali na baklub, masano mpe misala ya kultura.',
    statStudents: 'Bayekoli Basengami',
    statPrograms: 'Maprogram ya Boyebi',
    statRate: 'Mokano ya Mosala',
    statYears: 'Bambula ya Boyebi',
    progLabel: 'Maprogram na biso',
    progTitle: 'Yeba Mikanda na biso',
    progSub: 'Yeba maprogram manso mpo na kobundela mikakatano ya mokili ya sika.',
    learnMore: 'Yeba mingi',
    viewAll: 'Tala maprogram manso',
    newsLabel: 'Mambu ya sika',
    newsTitle: 'Bomoi ya Campus mpe Bayokani',
    newsSub: 'Zala na boyebi ya mambu ya sika, bayokani mpe bilongi ya lisanga na biso ya université.',
    readMore: 'Tanga mingi',
    tagEnrollment: 'Bosengami',
    tagExcellence: 'Bolongi',
    tagPartnership: 'Boyokani',
    news1Title: 'Mokolo ya nsuka ya bosengami ekomi',
    news1Desc: 'Bosengami mpo na mobu ya kelasi 2026-2027 efungwami. Senga liboso ya sanza ya nsambo 30.',
    news2Title: 'UPK elongi Championnat National',
    news2Desc: 'Timɛ na biso ya debate elongi esika ya yambo na championnat national inter-universitaire.',
    news3Title: 'Boyokani ya sika ya mokili mobimba',
    news3Desc: 'UPK esali boyokani ya kosangana na Université Paris-Saclay mpo na bobongoli ya kelasi.',
    ctaTitle: 'Obongisi mpo na kosangana na UPK?',
    ctaSub: 'Mokapo ya yambo mpo na libaku ya kitoko. Bosengemi efungwami mpo na mobu ya kelasi 2026-2027.',
    ctaApply: 'Senga sikoyo',
    ctaContact: 'Boyokani na biso',
    aboutTitle: 'Mpo na Université Progressiste de Kinshasa',
    aboutDesc: 'Université Progressiste de Kinshasa (UPK) ezali moko ya ba institutions ya likolo koleka na République Démocratique du Congo. Ebandaki na mokano ya kopesa boyebi oyo ekoki mpe ya kitoko, UPK ekomi esika ya kopela ya boyekoli mpe bolukiluki.',
    missionTitle: 'Misio na biso',
    missionDesc: 'Kokolisa bokoli ya mayele, kotombola boyebi ya likolo, mpe kobongisa bakonzi ya libaku oyo bakosala mpo na bokoli socio-économique ya ekolo mpe mokili.',
    visionTitle: 'Vizio na biso',
    visionDesc: 'Koyebana na mokili mobimba lokola université oyo etambwisa bobwasi, bolukiluki mpe boyebi ya mobimba na Afrika.',
    facultiesLoading: 'Kozwa mikanda...',
    facultiesError: 'Ezali difficile kozwa mikanda sikoyo.',
    facultiesErrorTitle: 'Libungi ekomi',
    facultiesRetry: 'Meka lisusu',
    facultiesBannerLabel: 'Boyebi ya likambo',
    facultiesTitle: 'Mikanda na biso',
    facultiesSub: 'Yeba mikanda na biso mpe zwa programme oyo ekoki na baambitions na yo.',
    facultiesEmpty: 'Mikanda moko te ezali',
    departments: 'Departemá',
    facultiesCtaTitle: 'Obongisi mpo na kosangana na UPK?',
    facultiesCtaSub: 'Bosengemi efungwami. Senga sikoyo mpo na mobu ya kelasi 2026-2027.',
    facultiesCtaBtn: 'Senga sikoyo',
    loginTitle: 'Boyei malamu lisusu',
    loginNoAccount: 'Ozali na compte te?',
    loginApply: 'Senga mpo na kokota',
    loginEmailLabel: 'Adres email',
    loginPasswordLabel: 'Mokanda ya sekele',
    loginEmailPlaceholder: 'Tiya email na yo',
    loginPasswordPlaceholder: 'Tiya mokanda ya sekele na yo',
    loginRemember: 'Kanisa ngai',
    loginForgot: 'Okanisi mokanda ya sekele te?',
    loginButton: 'Kota',
    loginFailed: 'Kota esili mabe. Tala ba identificants na yo.',
    loginSuccess: 'Compte esalami malamu! Tala email na yo mpe fungwa lien ya konfirmasyon liboso ya kokota.',
    loginVerified: 'Email endimami malamu! Okoki kokota sikoyo.',
    regTitle: 'Mobembo na yo ebandi',
    regHaveAccount: 'Ozali na compte déjà?',
    regSignIn: 'Kota',
    regFirstName: 'Kombo ya liboso',
    regLastName: 'Kombo ya suka',
    regEmailLabel: 'Adres email',
    regPasswordLabel: 'Mokanda ya sekele',
    regConfirmLabel: 'Tiya mokanda ya sekele lisusu',
    regFirstNamePlaceholder: 'Kombo ya liboso',
    regLastNamePlaceholder: 'Kombo ya suka',
    regEmailPlaceholder: 'Tiya email na yo',
    regPasswordPlaceholder: 'Mokanda ya sekele',
    regConfirmPlaceholder: 'Tiya mokanda ya sekele lisusu',
    regButton: 'Kela Compte',
    regRule8_16: 'Bilembo 8-16',
    regRuleUpper: '1 lettre monene',
    regRuleLower: '1 lettre moke',
    regRuleNumber: '1 nomero',
    regRuleSpecial: '1 elembo ya spécial',
    regMatch: 'Mikanda ya sekele ezali ndenge moko',
    regNoMatch: 'Mikanda ya sekele ekokani te',
    regPasswordError: 'Mokanda ya sekele etindami te.',
    regConfirmError: 'Mikanda ya sekele ekokani te.',
    regEmailSent: 'Tala email na yo',
    regEmailSentDesc: 'Email ya konfirmasyon etindami na',
    regStepsTitle: 'Bakapo oyo elandi:',
    regStep1: 'Fungwa boite ya réception na yo',
    regStep2: 'Fungwa lien ya konfirmasyon',
    regStep3: 'Compte na yo ekopelama automatiquement',
    regStep4: 'Kota na identificants na yo',
    regLinkExpiry: 'Lien ezali valable mpo na ngonga 2.',
    regGoLogin: 'Kende na connexion',
    regNotReceived: 'Ozwi email te? Tala spams na yo to',
    regResend: 'tinda lien lisusu',
    regResendSuccess: 'Email ya sika ya vérification etindami.',
    regResendError: 'Libungi na kotinda lisusu. Meka lisusu.',
    regSubmitError: 'Libungi ekomi na ntango ya bosengi.',

    contactTitle: 'Boyokani na biso',
    contactDesc: 'Ozali na mituna na ntina ya bosengi to maprogram? Timɛ na biso ezali awa mpo na kosunga yo.',
    contactVisit: 'Koya komona biso',
    contactCall: 'Benga biso',
    contactEmailTitle: 'Komela biso',
    contactPhone2: '+243 82 000 0000',
    contactEmail2: 'admissions@upk-kinshasa.net',

    verifyLoading: 'Botɛlɛmɛli ya email na yo ezali koya...',
    verifySuccess: 'Email Endimami!',
    verifySuccessMsg: 'Email endimami malamu!',
    verifyGoLogin: 'Kende na connexion',
    verifyFail: 'Botɛlɛmɛli ebungi',
    verifyMissingToken: 'Token ya botɛlɛmɛli ezangi. Tɔmba ozali kofungwa lien ya mobimba uta na email.',
    verifyExpired: 'Lien ya botɛlɛmɛli ezali mabe to eleki. Sɛnga compte ya sika to boyokani na support.',
    verifyHint: 'Tɔmba ozali kosalela lien ya sikasika uta na email na yo. Lien moko ekosalelama mbala moko mpé ekufa na ngonga 2.',
    verifyNewAccount: 'Kela compte ya sika',
    verifyBack: 'Zonga',
  },
  lua: {
    dashboard: 'Dashboard',
    admissionForm: 'Fomu wa kuyila',
    documents: 'Mikanda',
    settings: 'Malongolodi',
    student: 'Muyidi',
    portal: 'Portal',
    studentPortal: 'Portal wa Muyidi',
    logout: 'Bika',
    applicant: 'Musengi',
    applicationStatus: 'Malu a busengi',
    academicYear: 'Tshidimu tsha masomo 2026-2027',
    draft: 'Brouillon',
    submitted: 'Bitumibwe',
    underReview: 'Bidi bitangila',
    decision: 'Tshibelu',
    continueApplication: 'Kobesha busengi',
    requiredDocuments: 'Mikanda idi ikengela',
    identityCard: 'Carte d identite',
    academicTranscript: 'Releve wa masomo',
    passportPhoto: 'Foto passeport',
    uploadMissing: 'Tuma bidi bipanga',
    recentNotifications: 'Mayebisha a nshikidilu',
    settingsIntro: 'Sola munu wa mudimu ne fond.',
    language: 'Munu',
    industrialBackground: 'Fond industriel',
    appearance: 'Muenekelu',
    lightMode: 'Mode wa butoke',
    darkMode: 'Mode wa mudima',

    navHome: 'Nshibo',
    navAbout: 'Bualu',
    navFaculties: 'Mikanda',
    navContact: 'Kutongana',
    logIn: 'Kuyila',
    applyNow: 'Kusenga',
    whatsappLabel: 'Tusonele',
    uniName: 'Université Progressiste de Kinshasa',
    footerDesc: 'Kupa bukome ku tshikondo tshintu tshi bayile ku Repubilka ya Demokrasia ya Congo mu bupele budi bukata mu diji, ditangila ne kushintulula.',
    quickLinks: 'Mukanda wa kufikisha',
    aboutUs: 'Bualu budi',
    facultiesTitle: 'Mikanda',
    admissions: 'Busengi',
    contactTitle: 'Kutongana',
    addressLine1: 'Nshila wa 15, Limete Industriel',
    addressLine2: 'Kinshasa, RDC',
    contactEmail: 'info@upk-kinshasa.net',
    contactPhone: '+243 81 000 0000',
    privacy: 'Mikanda ya kusungila',
    terms: 'Malu a kudila',
    rights: 'Makalu onso asungibue.',
    heroBadge: 'Bupele budi bukata bukaye ku 1994',
    heroTitle: 'Bangula tshikondo tshobe ku',
    heroHighlight: 'Université Progressiste de Kinshasa',
    heroSub: 'Kulonga tshikondo tshintu tshi bayile mu dijina diakane mu dijina mu Repubilka ya Demokrasia ya Congo.',
    heroCta: 'Senga bukota',
    heroDiscover: 'Yuka UPK',
    trustEsu: 'Buela bwa Ministère ya ESU',
    trustAuf: 'Mwana wa AUF',
    trustIntl: 'Badipuloma bayukibwa pa ntanda yonso',
    whyLabel: 'Bualu ne tussole',
    whyTitle: 'Bualu ne Tussole UPK?',
    whySub: 'Tupele bupele budi bukata bwa ntanda yonso bubangulwa ku kulongoja ku malu.',
    whyCard1Title: 'Bupele Bwa Diji',
    whyCard1Desc: 'Baprofesa bêtu ba mushinku ne bayuki ba kazadi bêku kupele bupele bwa kanyenga, kusangisha dijina ne kazadi.',
    whyCard2Title: 'Bilumbulu Bia Mpa',
    whyCard2Desc: 'Balabwalu ba mushindu, babiliotèki ba kukana ne bakelasi ba mpa bubangulwa ku kulesha.',
    whyCard3Title: 'Bumi Bwa Campus Bwa Bushinta',
    whyCard3Desc: 'Sangana na mabumba a bayidi eshale benji bakukolesha mu baklub, masamba ne bikadilu biakane.',
    statStudents: 'Bayidi Bafikishe',
    statPrograms: 'Maprogramu a Diji',
    statRate: 'Kanyenga ka Kazadi',
    statYears: 'Bimye bya Bupele',
    progLabel: 'Maprogramu Étudiants',
    progTitle: 'Yuka Mikanda Yetu',
    progSub: 'Yuka maprogramu onso bubangulwa ku kumanya milwisho wa ntanda ya mpa.',
    learnMore: 'Dijina diakane',
    viewAll: 'Tala maprogramu onso',
    newsLabel: 'Mayebisha',
    newsTitle: 'Bumi bwa Campus ne Bikapua',
    newsSub: 'Kala na mayebisha a malu a mpa, bikapua ne bilumbulu bya mabumba étu a université.',
    readMore: 'Tanga diakane',
    tagEnrollment: 'Kufikisha',
    tagExcellence: 'Bupele',
    tagPartnership: 'Bukoleshi',
    news1Title: 'Tshibangilu tsha kufikisha tshidi tshikaye',
    news1Desc: 'Kufikisha ku tshidimu tsha masomo 2026-2027 kudi kufungua. Senga kabidi wa July 30.',
    news2Title: 'UPK Iwina Championnat National',
    news2Desc: 'Timu yetu ya débat iwina kanyenga ka ntete ku championnat national inter-universitaire.',
    news3Title: 'Bukoleshi Bwa Mpa Bwa Ntanda Yonso',
    news3Desc: 'UPK isaina lukumbu lwa bukoleshi na Université Paris-Saclay ku malu a masomo.',
    ctaTitle: 'Obangula Kujinga na UPK?',
    ctaSub: 'Tshimpindu tsha ntete ku tshikondo tshidi tshipe. Busengi bufungua ku tshidimu tsha masomo 2026-2027.',
    ctaApply: 'Senga Nsaa Yayi',
    ctaContact: 'Tutongane',
    aboutTitle: 'Bualu budi mu Université Progressiste de Kinshasa',
    aboutDesc: 'Université Progressiste de Kinshasa (UPK) idi imo ya binangu bya kanyenga mu Repubilka ya Demokrasia ya Congo. Yatunda na mushindu wa kupele diji dyakane dya kukana, UPK yatekama kikulu kya kutangila ne kushintulula.',
    missionTitle: 'Mushindu Wetu',
    missionDesc: 'Kukolesha bukuuku bua mayele, kulesha bupele bua diji, ne kulonga bayile ba tshikondo abo bakapela malu a kulonga mu kukola kwa ntanda ne kwa malu.',
    visionTitle: 'Tshimona Tshietu',
    visionDesc: 'Kuyukibwa pa ntanda yonso nga université itamba kutambwisha kushintulula, kuditangila ne diji dya bukale mu Afrika.',
    facultiesLoading: 'Kusenda mikanda...',
    facultiesError: 'Kupata mikanda kudi kukalu nsaa yayi.',
    facultiesErrorTitle: 'Tshilubi tshifiki',
    facultiesRetry: 'Esha',
    facultiesBannerLabel: 'Bupele bua diji',
    facultiesTitle: 'Mikanda Yetu',
    facultiesSub: 'Yuka mikanda yetu ne pata maprogramu aya akoke na biloolo byobe.',
    facultiesEmpty: 'Mikanda mbone mupatikana',
    departments: 'Madipatema',
    facultiesCtaTitle: 'Obangula Kujinga na UPK?',
    facultiesCtaSub: 'Busengi bufungua. Senga nsaa yayi ku tshidimu tsha masomo 2026-2027.',
    facultiesCtaBtn: 'Senga Nsaa Yayi',
    loginTitle: 'Muyi Mwambuluke',
    loginNoAccount: 'Ukaye na compte?',
    loginApply: 'Senga bukota',
    loginEmailLabel: 'Email adresse',
    loginPasswordLabel: 'Kanua a sishimba',
    loginEmailPlaceholder: 'Tula email yobe',
    loginPasswordPlaceholder: 'Tula kanua a sishimba kobe',
    loginRemember: 'Kanuka anga',
    loginForgot: 'Udi wakambana kanua a sishimba?',
    loginButton: 'Kota',
    loginFailed: 'Kota kwafumine. Tala ba identificants obe.',
    loginSuccess: 'Compte yabangwa mwanda! Tala email yobe ne tonda lien ya konfirmasyon kabidi wa kunyingila.',
    loginVerified: 'Email yemukejibwa mwanda! Ukoke kunyingila nsaa yayi.',
    regTitle: 'Tanda Tshikondo Tshobe',
    regHaveAccount: 'Ukaye na compte?',
    regSignIn: 'Kota',
    regFirstName: 'Dina Dya Ntete',
    regLastName: 'Dina Dya Mpa',
    regEmailLabel: 'Email adresse',
    regPasswordLabel: 'Kanua a sishimba',
    regConfirmLabel: 'Tula kanua a sishimba kobe neyi',
    regFirstNamePlaceholder: 'Dina dya ntete',
    regLastNamePlaceholder: 'Dina dya mpa',
    regEmailPlaceholder: 'Tula email yobe',
    regPasswordPlaceholder: 'Kanua a sishimba',
    regConfirmPlaceholder: 'Tula kanua a sishimba neyi',
    regButton: 'Banga Compte',
    regRule8_16: 'Bilembo 8-16',
    regRuleUpper: '1 letre mune',
    regRuleLower: '1 letre mubi',
    regRuleNumber: '1 nombro',
    regRuleSpecial: '1 elembo ya special',
    regMatch: 'Bikanua bia sishimba bidi nka benda',
    regNoMatch: 'Bikanua bia sishimba bibenda',
    regPasswordError: 'Kanua a sishimba kakoke na milongo yonso.',
    regConfirmError: 'Bikanua bia sishimba bibenda.',
    regEmailSent: 'Tala email yobe',
    regEmailSentDesc: 'Email ya konfirmasyon yatumibwa ku',
    regStepsTitle: 'Bitshipa bia kulanda:',
    regStep1: 'Fungua boite ya reception yobe',
    regStep2: 'Tonda lien ya konfirmasyon',
    regStep3: 'Compte yobe ikapelama automatiquement',
    regStep4: 'Kota na identificants obe',
    regLinkExpiry: 'Lien idi na ngolu ku diola 2.',
    regGoLogin: 'Enda ku connexion',
    regNotReceived: 'Wanyi email? Tala spams obe to',
    regResend: 'tuma lien neyi',
    regResendSuccess: 'Email ya mpa ya vérification yatumibwa.',
    regResendError: 'Tshilubi ku kutama neyi. Esha.',
    regSubmitError: 'Tshilubi tshifiki pa tshimpindu tsha kusenga.',

    contactTitle: 'Tutongane',
    contactDesc: 'Una mafuku na nsenga ya kuyila to maprogramu? Timu yetu idi kuno ku kukwasha.',
    contactVisit: 'Tutu tala',
    contactCall: 'Tubingile',
    contactEmailTitle: 'Tutumine email',
    contactPhone2: '+243 82 000 0000',
    contactEmail2: 'admissions@upk-kinshasa.net',

    verifyLoading: 'Kutala email yobe...',
    verifySuccess: 'Email Yemukejibwa!',
    verifySuccessMsg: 'Email yemukejibwa neyi!',
    verifyGoLogin: 'Enda ku kuyila',
    verifyFail: 'Kwemukeja Kwafumine',
    verifyMissingToken: 'Token ya kwemukeja wanyi. Tala ne watonda lien wa kukana uta email.',
    verifyExpired: 'Lien wa kwemukeja wafumine. Banga compte wa mpa to wakane na support.',
    verifyHint: 'Tala ne usambilayi lien wa mupepe uta email. Lien umo wakoke kusambilwa kimune ne waumi ku diola 2.',
    verifyNewAccount: 'Banga compte wa mpa',
    verifyBack: 'Bwela',
  },
  kg: {
    dashboard: 'Dashboard',
    admissionForm: 'Fomu ya kukota',
    documents: 'Mikanda',
    settings: 'Bibongisila',
    student: 'Longoki',
    portal: 'Portal',
    studentPortal: 'Portal ya Longoki',
    logout: 'Basika',
    applicant: 'Nsengi',
    applicationStatus: 'Kifuani kia nsengolo',
    academicYear: 'Mvu ya malongi 2026-2027',
    draft: 'Brouillon',
    submitted: 'Yatumama',
    underReview: 'Na tala',
    decision: 'Nzengolo',
    continueApplication: 'Landila nsengolo',
    requiredDocuments: 'Mikanda mi mfunu',
    identityCard: 'Carte ya identité',
    academicTranscript: 'Releve ya malongi',
    passportPhoto: 'Foto passeport',
    uploadMissing: 'Tula yina kele ve',
    recentNotifications: 'Mayebisi ya mpa',
    settingsIntro: 'Sola ndinga ya kisalu mpe fond.',
    language: 'Ndinga',
    industrialBackground: 'Fond industriel',
    appearance: 'Monika',
    lightMode: 'Mode ya nsemo',
    darkMode: 'Mode ya mpimpa',

    navHome: 'Kimpwanza',
    navAbout: 'Mambu',
    navFaculties: 'Mikanda',
    navContact: 'Kuwakana',
    logIn: 'Kota',
    applyNow: 'Senga',
    whatsappLabel: 'Sonikela beto',
    uniName: 'Université Progressiste de Kinshasa',
    footerDesc: 'Kupesa ngolo na kikuma kya bantwadisi na Repubilika ya Kongo ya Dimokalasi na nzila ya kiyeku yai mbote na dilongi, kutombola mpe kusala mpa.',
    quickLinks: 'Bikalulu ya mbote',
    aboutUs: 'Mambu na beto',
    facultiesTitle: 'Mikanda',
    admissions: 'Nsengolo',
    contactTitle: 'Kuwakana',
    addressLine1: 'Nzila 15, Limete Industriel',
    addressLine2: 'Kinshasa, RDC',
    contactEmail: 'info@upk-kinshasa.net',
    contactPhone: '+243 81 000 0000',
    privacy: 'Mibeko ya kisungi',
    terms: 'Mibeko ya kisadilu',
    rights: 'Bakiese yonso yikele.',
    heroBadge: 'Kiyeku yai mbote tuka 1994',
    heroTitle: 'Bongisa kielekezi na nge na',
    heroHighlight: 'Université Progressiste de Kinshasa',
    heroSub: 'Kulonga kikuma kya ntete kya bantwadisi na nzila ya dilongi ya mputu, kutombola mpe kusala mpa na ntima ya RDC.',
    heroCta: 'Senga Kukota',
    heroDiscover: 'Zaba UPK',
    trustEsu: 'Kendimama na Ministère ya ESU',
    trustAuf: 'Muntu ya AUF',
    trustIntl: 'Badipuloma bazabanaka na mputu',
    whyLabel: 'Sambu na nki kusola beto',
    whyTitle: 'Sambu na nki Kusola UPK?',
    whySub: 'Beto kepesaka dilongi ya kimputu yina yalongomaka sambu na kulungisa nge.',
    whyCard1Title: 'Kiyeku yai Mbote',
    whyCard1Desc: 'Baprofese na beto ya kuzabanaka mpe bayekuluzi ya kisalu kekabaka dilongi ya kiyeku yai kuluta, kusangisa mambu ya dilongi mpe ya kisalu.',
    whyCard2Title: 'Bisadilu ya Mpa',
    whyCard2Desc: 'Balabo ya nsuka, babuku ya kukana mpe bakelasi ya mpa yina yalongomaka sambu na kutombola malongi.',
    whyCard3Title: 'Kuzinga na Campus',
    whyCard3Desc: 'Kota na kimvuka ya balongi ya kuswaswana yina kewakana na baklub, masano mpe bisalu ya kultura.',
    statStudents: 'Balongi Bakotisaka',
    statPrograms: 'Maprogram ya Malongi',
    statRate: 'Kiteso ya Kisalu',
    statYears: 'Bamvu ya Kiyeku',
    progLabel: 'Maprogram na Beto',
    progTitle: 'Zaba Mikanda na Beto',
    progSub: 'Zaba maprogram ya kuswaswana yina yalongomaka sambu na kukutana na mambu ya ntama ya mvu.',
    learnMore: 'Zaba mingi',
    viewAll: 'Tala maprogram yonso',
    newsLabel: 'Mambu ya mpa',
    newsTitle: 'Kuzinga na Campus mpe Mambu',
    newsSub: 'Kala na mayebisi ya mambu ya mpa, mambu mpa mpe kulunga ya kimvuka na beto ya universite.',
    readMore: 'Tanga mingi',
    tagEnrollment: 'Kotisila',
    tagExcellence: 'Kiyeku',
    tagPartnership: 'Kuwakana',
    news1Title: 'Kilumbu ya nsuka ya Kotisila Kele',
    news1Desc: 'Kotisila sambu na mvu ya malongi 2026-2027 kefungwa. Senga na ntwala ya kilumbu 30 ya ngonda ya nsambwadi.',
    news2Title: 'UPK Yalungisa Championnat National',
    news2Desc: 'Timu na beto ya debate yalungisa kisika ya ntete na championnat national inter-universitaire.',
    news3Title: 'Kuwakana Kwa Mpa Kwa Kimputu',
    news3Desc: 'UPK kesakana kuwakana ya kusala kumosi na Universite ya Paris-Saclay sambu na kuwakanisa balongi.',
    ctaTitle: 'Wekwami Kukota na UPK?',
    ctaSub: 'Bula lutambi ya ntete na kielekezi ya mbote. Kotisila kefungwa sambu na mvu ya malongi 2026-2027.',
    ctaApply: 'Senga Ntangu Yayi',
    ctaContact: 'Wakana na Beto',
    aboutTitle: 'Mambu na Universite Progressiste de Kinshasa',
    aboutDesc: 'Universite Progressiste de Kinshasa (UPK) kele mosi ya binangu ya ntete ya dilongi ya mputu na Repubilika ya Kongo ya Dimokalasi. Yatungamaka na mukumba ya kupesa dilongi ya kukana mpe ya mbote, UPK yekwama kima ya kuyokula ya kulonga mpe kutombola.',
    missionTitle: 'Misio na Beto',
    missionDesc: 'Kutombola kuyela ya mayele, kupesa kiyeku yai ya dilongi, mpe kulonga bantwadisi ya ntama yina kakonza mambu ya mfunu na kimvwama ya insi mpe ya mputu.',
    visionTitle: 'Meso na Beto',
    visionDesc: 'Kuzabanaka na mputu bonso universite yina ke tambwisa kusala mpa, kutombola mpe dilongi ya mvimba na Afrika.',
    facultiesLoading: 'Kubaka mikanda...',
    facultiesError: 'Kukota kukota mikanda ntangu yayi.',
    facultiesErrorTitle: 'Mfuka mekwisa',
    facultiesRetry: 'Meka diaka',
    facultiesBannerLabel: 'Kiyeku yai dilongi',
    facultiesTitle: 'Mikanda na Beto',
    facultiesSub: 'Zaba mikanda na beto mpe kuwusa programa yina ke wakana na mpusa na nge.',
    facultiesEmpty: 'Mikanda mosi ve',
    departments: 'Badiparterna',
    facultiesCtaTitle: 'Wekwami Kukota na UPK?',
    facultiesCtaSub: 'Kotisila kefungwa. Senga ntangu yayi sambu na mvu ya malongi 2026-2027.',
    facultiesCtaBtn: 'Senga Ntangu Yayi',
    loginTitle: 'Mbote Muntu Zaya',
    loginNoAccount: 'Nge kele ti compte?',
    loginApply: 'Senga sambu na kukota',
    loginEmailLabel: 'Adresse email',
    loginPasswordLabel: 'Mfinda ya nkaka',
    loginEmailPlaceholder: 'Kotisa email na nge',
    loginPasswordPlaceholder: 'Kotisa mfinda ya nkaka na nge',
    loginRemember: 'Yibuka mono',
    loginForgot: 'Mfinda ya nkaka na nge ilobaka?',
    loginButton: 'Kota',
    loginFailed: 'Kota kusalama ve. Tala ba identifiants na nge.',
    loginSuccess: 'Compte yekwama mbote! Tala email na nge mpe nika lien ya konfirmasyon na ntwala ya kukota.',
    loginVerified: 'Email yendimama mbote! Nge lenda kota ntangu yayi.',
    regTitle: 'Yantika Nzietolo na Nge',
    regHaveAccount: 'Nge kele ti compte?',
    regSignIn: 'Kota',
    regFirstName: 'Zina ya Ntete',
    regLastName: 'Zina ya Nsuka',
    regEmailLabel: 'Adresse email',
    regPasswordLabel: 'Mfinda ya nkaka',
    regConfirmLabel: 'Tia mfinda ya nkaka diaka',
    regFirstNamePlaceholder: 'Zina ya ntete',
    regLastNamePlaceholder: 'Zina ya nsuka',
    regEmailPlaceholder: 'Kotisa email na nge',
    regPasswordPlaceholder: 'Mfinda ya nkaka',
    regConfirmPlaceholder: 'Tia mfinda ya nkaka diaka',
    regButton: 'Tunga Compte',
    regRule8_16: 'Biti 8-16',
    regRuleUpper: '1 letre ya nene',
    regRuleLower: '1 letre ya fioti',
    regRuleNumber: '1 numero',
    regRuleSpecial: '1 elembo ya spesia',
    regMatch: 'Bifinda ya nkaka bikwenda',
    regNoMatch: 'Bifinda ya nkaka bikwendaka ve',
    regPasswordError: 'Mfinda ya nkaka ke landaka mibeko yonso ve.',
    regConfirmError: 'Bifinda ya nkaka bikwendaka ve.',
    regEmailSent: 'Tala email na nge',
    regEmailSentDesc: 'Email ya konfirmasyon yatumamaka na',
    regStepsTitle: 'Bipala ya kulanda:',
    regStep1: 'Fungula boite ya reception na nge',
    regStep2: 'Nika lien ya konfirmasyon',
    regStep3: 'Compte na nge yekwama automatiquement',
    regStep4: 'Kota na identifiants na nge',
    regLinkExpiry: 'Lien kele valable sambu na bangunga 2.',
    regGoLogin: 'Kwenda na connexion',
    regNotReceived: 'Email mekwisa ve? Tala spams na nge to',
    regResend: 'tinda lien diaka',
    regResendSuccess: 'Email ya mpa ya verifikasio yatumamaka.',
    regResendError: 'Mfuka ya kutinda diaka. Meka diaka.',
    regSubmitError: 'Mfuka mekwisa na ntangu ya kusenga.',

    contactTitle: 'Wakana na Beto',
    contactDesc: 'Ke ti mafuku na mambu ya kotisila to maprogram? Timu na beto kele awa sambu na kusansa nge.',
    contactVisit: 'Kwisa Kumona Beto',
    contactCall: 'Binga Beto',
    contactEmailTitle: 'Tindela Beto Email',
    contactPhone2: '+243 82 000 0000',
    contactEmail2: 'admissions@upk-kinshasa.net',

    verifyLoading: 'Kekudila email ya nge...',
    verifySuccess: 'Email Kendimama!',
    verifySuccessMsg: 'Email kendimama mbote!',
    verifyGoLogin: 'Kwenda na connexion',
    verifyFail: 'Kwendima Kusalama Ve',
    verifyMissingToken: 'Token ya kudima kele ve. Tala sambu nge menika lien ya mvimba tuka na email.',
    verifyExpired: 'Lien ya kudima kele mbi to meluta. Sala compte ya mpa to wakana na support.',
    verifyHint: 'Tala sambu nge kesadila lien ya sika tuka email na nge. Lien mosi kesalama fioti mosi mpembeni kansi meluta na bangunga 2.',
    verifyNewAccount: 'Sala compte ya mpa',
    verifyBack: 'Kuvutuka',
  }
};

const SettingsContext = createContext(null);

const getStoredSettings = () => {
  try {
    const storedSettings = {
      ...defaultSettings,
      ...JSON.parse(localStorage.getItem('ulk_student_settings'))
    };

    if (storedSettings.language === 'rw') {
      storedSettings.language = 'ln';
    }

    return storedSettings;
  } catch {
    return defaultSettings;
  }
};

export const SettingsProvider = ({ children }) => {
  const [settings, setSettings] = useState(getStoredSettings);

  const backgroundClass = useMemo(
    () => `${backgroundClasses[settings.background] || backgroundClasses.steel} ${settings.theme === 'dark' ? 'theme-dark-surface' : ''}`,
    [settings]
  );

  useEffect(() => {
    localStorage.setItem('ulk_student_settings', JSON.stringify(settings));
    document.documentElement.lang = settings.language;
    document.documentElement.classList.toggle('theme-dark', settings.theme === 'dark');


  }, [settings, backgroundClass]);

  const value = useMemo(() => {
    const lang = translations[settings.language] || translations.en;
    const t = new Proxy(lang, {
      get: (target, prop) => target[prop] ?? translations.en[prop] ?? prop,
    });

    return {
      settings,
      t,
      backgroundClass,
      updateSetting: (key, value) => setSettings((current) => ({ ...current, [key]: value }))
    };
  }, [settings, backgroundClass]);

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => useContext(SettingsContext);
