# Generated by Django 4.2.30 on 2026-05-23 14:18

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DIPLOMA', "Diplôme d'État / Certificat"), ('TRANSCRIPT', 'Relevé de notes'), ('PHOTO', 'Photo Passeport'), ('BIRTH_CERTIFICATE', 'Acte de Naissance'), ('ID_CARD', "Carte d'Identité / Passeport")], max_length=30)),
                ('file', models.FileField(upload_to='applications/documents/', validators=[documents.models.validate_file_extension, documents.models.validate_file_size])),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication')),
            ],
            options={
                'db_table': 'documents',
                'unique_together': {('application', 'document_type')},
            },
        ),
    ]
