# Generated by Django 4.2.30 on 2026-05-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('MPESA', 'M-Pesa (Vodacom)'), ('AIRTEL', 'Airtel Money'), ('ORANGE', 'Orange Money'), ('MOBILE_MONEY', 'Mobile Money (Afriland/Rawbank)')], max_length=20)),
                ('phone_number', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESSFUL', 'Réussi'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.admissionapplication')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
